author: Maksim Smirnov

title: Maksim Smirnov
tagline: "Principal Technical Lead & Software Engineer"

baseurl: ""

url: https://smirnoffmg.dev
github_username: smirnoffmg

# Contact info
email: "smirnoffmg@gmail.com"
linkedin: "hello-maksim-smirnov"
github: smirnoffmg
telegram: "smirnov_maksim_grigorevich"
description: "Principal Technical Lead and Software Engineer with 10+ years of experience in Python, Go, cloud architecture (AWS), and engineering leadership. Currently at Raiffeisenbank."
image: https://github.com/smirnoffmg.png

plugins:
  - jekyll-sitemap

# Google Analytics
google_analytics: G-4HG9NVZRVF

# Yandex Metrika
yandex_metrika: 105809801

# Remote theme
remote_theme: smirnoffmg/harvard-style-cv-theme
